In [84]:
import torch
import torch.nn.functional as F


In [85]:
kernel_size = (2,2)

In [86]:
t = torch.Tensor(kernel_size[0])

In [137]:
inp = torch.Tensor([[[[1,2,3,4],[5,6,7,8],[9,10,11,12]]],[[[10,20,30,40],[5,6,7,8],[9,10,11,12]]]])
print(inp.shape)
unfold = torch.nn.Unfold((2,2), dilation=1, padding=0, stride=1)

torch.Size([2, 1, 3, 4])


In [138]:
conv_groups = unfold(inp).transpose(1, 2)#.unfold(2,4,6)
print(conv_groups)
print(conv_groups.shape)

tensor([[[ 1.,  2.,  5.,  6.],
         [ 2.,  3.,  6.,  7.],
         [ 3.,  4.,  7.,  8.],
         [ 5.,  6.,  9., 10.],
         [ 6.,  7., 10., 11.],
         [ 7.,  8., 11., 12.]],

        [[10., 20.,  5.,  6.],
         [20., 30.,  6.,  7.],
         [30., 40.,  7.,  8.],
         [ 5.,  6.,  9., 10.],
         [ 6.,  7., 10., 11.],
         [ 7.,  8., 11., 12.]]])
torch.Size([2, 6, 4])


In [102]:
torch.sum(conv_groups,axis = 2)

tensor([[14., 18., 22., 30., 34., 38.]])

In [101]:
torch.sum(conv_groups,axis = 2).reshape((1,3,2))

tensor([[[14., 18.],
         [22., 30.],
         [34., 38.]]])

In [96]:
fold = torch.nn.Fold(output_size=(3,2), kernel_size=(2, 2),dilation=1, padding=0, stride=1)

In [97]:
fold(conv_groups)

RuntimeError: Expected size of input's dimension 1 to be divisible by the product of kernel_size, but got input.size(1)=6 and kernel_size=(2, 2).

In [89]:
t

tensor([8., nan])

In [30]:
t.reshape((2,2,2))

RuntimeError: shape '[2, 2, 2]' is invalid for input of size 2

In [59]:
import numpy as np
import math

In [17]:
math.prod([4,2])

8

In [46]:
mat = torch.tensor([[[1,2],[2,3]],[[1,2],[2,3]],[[1,2],[2,3]],[[1,2],[2,3]]])

In [47]:
t = torch.tensor([[[1,2,2,3],[1,2,2,3]],[[1,2,2,3],[1,2,2,3]]])

In [57]:
for ti in range(len(t[0,0])):
    print(t[:,:,ti])
    print(mat[ti]<t[:,:,ti])

tensor([[1, 1],
        [1, 1]])
tensor([[False, False],
        [False, False]])
tensor([[2, 2],
        [2, 2]])
tensor([[ True, False],
        [False, False]])
tensor([[2, 2],
        [2, 2]])
tensor([[ True, False],
        [False, False]])
tensor([[3, 3],
        [3, 3]])
tensor([[ True,  True],
        [ True, False]])


In [58]:
mat<t

RuntimeError: The size of tensor a (2) must match the size of tensor b (4) at non-singleton dimension 2

In [39]:
F.pad(t, (0,2), "constant", 1)

tensor([[1, 2, 1, 1],
        [2, 3, 1, 1]])

In [11]:
torch.tensor([1,22,3]).expand(20,-1)

tensor([[ 1, 22,  3],
        [ 1, 22,  3],
        [ 1, 22,  3],
        [ 1, 22,  3],
        [ 1, 22,  3],
        [ 1, 22,  3],
        [ 1, 22,  3],
        [ 1, 22,  3],
        [ 1, 22,  3],
        [ 1, 22,  3],
        [ 1, 22,  3],
        [ 1, 22,  3],
        [ 1, 22,  3],
        [ 1, 22,  3],
        [ 1, 22,  3],
        [ 1, 22,  3],
        [ 1, 22,  3],
        [ 1, 22,  3],
        [ 1, 22,  3],
        [ 1, 22,  3]])

In [12]:
torch.tensor([1,22,3,4]).view(2,2)

tensor([[ 1, 22],
        [ 3,  4]])