In [31]:
import torch
import torch.nn.functional as F


In [19]:
kernel_size = (2,2)

In [28]:
t = torch.Tensor(kernel_size[0])

In [29]:
t

tensor([0., 0.])

In [30]:
t.reshape((2,2,2))

RuntimeError: shape '[2, 2, 2]' is invalid for input of size 2

In [16]:
import numpy as np
import math

In [17]:
math.prod([4,2])

8

In [46]:
mat = torch.tensor([[[1,2],[2,3]],[[1,2],[2,3]],[[1,2],[2,3]],[[1,2],[2,3]]])

In [47]:
t = torch.tensor([[[1,2,2,3],[1,2,2,3]],[[1,2,2,3],[1,2,2,3]]])

In [57]:
for ti in range(len(t[0,0])):
    print(t[:,:,ti])
    print(mat[ti]<t[:,:,ti])

tensor([[1, 1],
        [1, 1]])
tensor([[False, False],
        [False, False]])
tensor([[2, 2],
        [2, 2]])
tensor([[ True, False],
        [False, False]])
tensor([[2, 2],
        [2, 2]])
tensor([[ True, False],
        [False, False]])
tensor([[3, 3],
        [3, 3]])
tensor([[ True,  True],
        [ True, False]])


In [58]:
mat<t

RuntimeError: The size of tensor a (2) must match the size of tensor b (4) at non-singleton dimension 2

In [39]:
F.pad(t, (0,2), "constant", 1)

tensor([[1, 2, 1, 1],
        [2, 3, 1, 1]])

In [11]:
torch.tensor([1,22,3]).expand(20,-1)

tensor([[ 1, 22,  3],
        [ 1, 22,  3],
        [ 1, 22,  3],
        [ 1, 22,  3],
        [ 1, 22,  3],
        [ 1, 22,  3],
        [ 1, 22,  3],
        [ 1, 22,  3],
        [ 1, 22,  3],
        [ 1, 22,  3],
        [ 1, 22,  3],
        [ 1, 22,  3],
        [ 1, 22,  3],
        [ 1, 22,  3],
        [ 1, 22,  3],
        [ 1, 22,  3],
        [ 1, 22,  3],
        [ 1, 22,  3],
        [ 1, 22,  3],
        [ 1, 22,  3]])

In [12]:
torch.tensor([1,22,3,4]).view(2,2)

tensor([[ 1, 22],
        [ 3,  4]])